### PR TITLE
task 1

### PR DESCRIPTION
**Pull request by juliaschoenwald**

### CODE REVIEW

**Review by rugbymann — APPROVED** [review]

**Review by nata-bo — APPROVED** [review]
Super!

**Review by AnnaRuk — APPROVED** [review]

**Review by MrKOT92 — APPROVED** [review]

**Review by GrinyaNat — APPROVED** [review]
good

**Review by KonstantinGlazunov — APPROVED** [review]
OK!

**Review by Tsarukyula — APPROVED** [review]
Well done!

**Comment by LeonidUsatii** [comment]
good

**Review by Natali-2023 — APPROVED** [review]
+

**Review by EliasFalke — APPROVED** [review]
Good Job!

**Review by Kristina0404 — APPROVED** [review]

**Pull request merged**
