### PR TITLE
task 1

### PR DESCRIPTION
**Pull request by GrinyaNat**

### CODE REVIEW

**Review by nata-bo — APPROVED** [review]
Super !

**Review by jurgita02 — APPROVED** [review]
Good job

**Review by AnnaRuk — APPROVED** [review]

**Review by viktoriaustymova — APPROVED** [review]

**Review by Tsarukyula — APPROVED** [review]
Well done!

**Review by rugbymann — APPROVED** [review]

**Review by KonstantinGlazunov — APPROVED** [review]
OK!

**Review by MrKOT92 — APPROVED** [review]

**Review by Natali-2023 — APPROVED** [review]
+

**Review by juliaschoenwald — APPROVED** [review]

**Pull request merged**
