### PR TITLE
task1

### PR DESCRIPTION
**Pull request by Natali-2023**

### CODE REVIEW

**Review by jurgita02 — APPROVED** [review]
Good job

**Review by GrinyaNat — APPROVED** [review]
super

**Review by nata-bo — APPROVED** [review]
Super!

**Review by viktoriaustymova — APPROVED** [review]

**Review by Tsarukyula — APPROVED** [review]
Well done!

**Review by KonstantinGlazunov — APPROVED** [review]
OK!

**Review by juliaschoenwald — APPROVED** [review]

**Review by KonstantinGlazunov — APPROVED** [review]
OK!

**Review by Kristina0404 — APPROVED** [review]
super

**Pull request merged**
