### PR TITLE
task1

### PR DESCRIPTION
**Pull request by IrynaSainozhenko**
Task1 is done

### CODE REVIEW

**Review by SSedakov — APPROVED** [review]
Good job

**Review by EliasFalke — APPROVED** [review]
Good Job!

**Review by jurgita02 — APPROVED** [review]
Good job

**Review by GrinyaNat — APPROVED** [review]
super

**Review by AnnaRuk — APPROVED** [review]

**Review by viktoriaustymova — APPROVED** [review]

**Comment by OksanaPatsii** [comment]
super

**Review by juliaschoenwald — APPROVED** [review]

**Review by Natali-2023 — APPROVED** [review]
+

**Review by KonstantinGlazunov — APPROVED** [review]
OK!

**Review by MrKOT92 — APPROVED** [review]

**Pull request merged**
