### PR TITLE
task1

### PR DESCRIPTION
**Pull request by SSedakov**

### CODE REVIEW

**Review by AndreiBakhtinov — APPROVED** [review]
Good Job!

**Review by rugbymann — APPROVED** [review]

**Review by Iren25 — APPROVED** [review]

**Review by AnnaRuk — APPROVED** [review]

**Review by MrKOT92 — APPROVED** [review]

**Review by jurgita02 — APPROVED** [review]
Good job

**Review by Tsarukyula — APPROVED** [review]
Well done!

**Comment by OksanaPatsii** [comment]
Super

**Review by KonstantinGlazunov — APPROVED** [review]
OK!

**Review by Natali-2023 — APPROVED** [review]
+

**Review by juliaschoenwald — APPROVED** [review]

**Pull request merged**
