### PR TITLE
task 1

### PR DESCRIPTION
**Pull request by Iren25**

### CODE REVIEW

**Review by AndreiBakhtinov — APPROVED** [review]
Good Job!

**Review by MrKOT92 — APPROVED** [review]

**Review by SSedakov — APPROVED** [review]

**Review by nata-bo — APPROVED** [review]
Super!

**Review by jurgita02 — APPROVED** [review]
Good job

**Review by Tsarukyula — APPROVED** [review]
Well done!

**Comment by LeonidUsatii** [comment]
good

**Comment by OksanaPatsii** [comment]
Super

**Review by KonstantinGlazunov — APPROVED** [review]
OK!

**Review by Natali-2023 — APPROVED** [review]
+

**Review by Kristina0404 — APPROVED** [review]
super!

**Review by GrinyaNat — APPROVED** [review]
ok

**Pull request merged**
