### PR TITLE
task1 daone

### PR DESCRIPTION
**Pull request by KonstantinGlazunov**

### CODE REVIEW

**Review by jurgita02 — APPROVED** [review]
Good job

**Review by EliasFalke — APPROVED** [review]
Good Job!

**Review by nata-bo — APPROVED** [review]
Super!

**Review by MrKOT92 — APPROVED** [review]

**Comment by OksanaPatsii** [comment]
Good job

**Review by viktoriaustymova — APPROVED** [review]

**Comment by LeonidUsatii** [comment]
good

**Review by Natali-2023 — APPROVED** [review]
+

**Review by Tsarukyula — APPROVED** [review]
Well done!

**Pull request merged**
