### PR TITLE
task 1

### PR DESCRIPTION
**Pull request by viktoriaustymova**

### CODE REVIEW

**Review by SSedakov — APPROVED** [review]

**Review by jurgita02 — APPROVED** [review]
Good job

**Review by GrinyaNat — COMMENTED** [review]
nice

**Review by Tsarukyula — APPROVED** [review]
Well done!

**Review by AnnaRuk — APPROVED** [review]

**Review by MrKOT92 — APPROVED** [review]

**Review by Iren25 — APPROVED** [review]

**Review by KonstantinGlazunov — APPROVED** [review]
OK!

**Review by nata-bo — APPROVED** [review]
Super!

**Review by Natali-2023 — APPROVED** [review]
+

**Review by juliaschoenwald — APPROVED** [review]

**Pull request merged**
